#! /bin/sh

set -e

ln -sf /usr/share/subsonic/subsonic.sh /usr/bin/subsonic

# Create transcoder symlinks.
mkdir -p /var/subsonic/transcode
chmod oug+rwx /var/subsonic

[ ! -e /var/subsonic/transcode/lame ]   && ln -sf /usr/bin/lame   /var/subsonic/transcode/
[ ! -e /var/subsonic/transcode/ffmpeg ] && ln -sf /usr/bin/ffmpeg /var/subsonic/transcode/
[ ! -e /var/subsonic/transcode/flac ]   && ln -sf /usr/bin/flac   /var/subsonic/transcode/
[ ! -e /var/subsonic/transcode/faad ]   && ln -sf /usr/bin/faad   /var/subsonic/transcode/
[ ! -e /var/subsonic/transcode/oggdec ] && ln -sf /usr/bin/oggdec /var/subsonic/transcode/
[ ! -e /var/subsonic/transcode/oggenc ] && ln -sf /usr/bin/oggenc /var/subsonic/transcode/

# Clear jetty cache.
rm -rf /var/subsonic/jetty

# Change user to root
chown -R root /var/subsonic
chown -R root /tmp/subsonic

# Configure Subsonic service.
update-rc.d subsonic defaults 99

# Start Subsonic service.
invoke-rc.d subsonic start
