#! /bin/sh

set -e

ln -s /usr/share/subsonic/subsonic.sh /usr/bin/subsonic

# Create transcoder symlinks.
mkdir -p /var/subsonic/transcode
chmod oug+rwx /var/subsonic
ln -sf /usr/bin/lame /var/subsonic/transcode/
ln -sf /usr/bin/ffmpeg /var/subsonic/transcode/
ln -sf /usr/bin/flac /var/subsonic/transcode/
ln -sf /usr/bin/faad /var/subsonic/transcode/
ln -sf /usr/bin/oggdec /var/subsonic/transcode/
ln -sf /usr/bin/oggenc /var/subsonic/transcode/

# Clear jetty cache.
rm -rf /var/subsonic/jetty

# Configure Subsonic service.
update-rc.d subsonic defaults 99

# Start Subsonic service.
invoke-rc.d subsonic start
